### ISSUE TITLE
ESLint v6 breaks importing path

### ISSUE THREAD

**Issue by keik** [zertosh/eslint-plugin-dependencies#20]
eslint-plugin-dependencies with ESLint v6 produce following error:

```
Error: Failed to load plugin 'dependencies' declared in '.eslintrc.js': Cannot find module './util/traverser'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at Object.<anonymous> (/Users/kato-kei/work/products/freee-payroll/node_modules/eslint-plugin-dependencies/no-cycles.js:29:30)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

At ESLint v6, `lib/util/traverser` was moved to `lib/shared/traverser`.
https://github.com/eslint/eslint/blob/v5.16.0/lib/util/traverser.js
https://github.com/eslint/eslint/blob/v6.0.0/lib/shared/traverser.js

I tried to fix this path at local environment and work fine.

**Comment by roniger** [comment]
Added pull request https://github.com/zertosh/eslint-plugin-dependencies/pull/21

**Comment by gabegorelick** [comment]
Still an issue. Should this project be considered abandoned?

**Comment by silencej** [comment]
> 
> 
> Still an issue. Should this project be considered abandoned?

@gabegorelick I found this https://www.npmjs.com/package/eslint-plugin-import which can replace this.
