### ISSUE TITLE
import error?

### ISSUE THREAD

**Issue by elangelo** [zertosh/eslint-plugin-dependencies#7]
ERROR in ./src/index.js                                                                                                                                           
Module build failed: Error: Cannot find module './util/traverser'                                                                                                 
    at Function.Module._resolveFilename (module.js:472:15)                                                                                                        
    at Function.Module._load (module.js:420:25)                                                                                                                   
    at Module.require (module.js:500:17)                                                                                                                          
    at Object.<anonymous> (/home/samuel/adam/adamui/client/node_modules/eslint-plugin-dependencies/no-cycles.js:24:30)                                            
    at Module._compile (module.js:573:32)                                                                                                                         
    at Object.Module._extensions..js (module.js:582:10)                                                                                                           
    at Module.load (module.js:490:32)                                                                                                                             
    at tryModuleLoad (module.js:449:12)                                                                                                                           
    at Function.Module._load (module.js:441:3)                                                                                                                    
    at Module.require (module.js:500:17)                                                                                                                          
    at require (internal/module.js:20:19)                                                                                                                         
    at Object.<anonymous> (/home/samuel/adam/adamui/client/node_modules/eslint-plugin-dependencies/index.js:6:18)

**Comment by zertosh** [comment]
What version of eslint do you have?
